spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_2
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
